# Generated by Django 5.0.6 on 2024-07-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='scores',
            field=models.JSONField(default=dict),
        ),
    ]
