# Generated by Django 5.0.6 on 2024-07-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_subject_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('user_id', models.IntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='', max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
