# Generated by Django 5.0.6 on 2024-07-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_botuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPostForBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('file', models.CharField(default='', max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
