# Generated by Django 5.0.6 on 2024-07-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_mainpostforbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpostforbot',
            name='post_id',
            field=models.IntegerField(default=0),
        ),
    ]
