# Generated by Django 5.0.6 on 2024-07-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_mainpostforbot_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpostforbot',
            name='why',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
