# Generated by Django 5.0.6 on 2024-07-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_mainpostforbot_why_alter_botuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpostforbot',
            name='enteties',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
