# Generated by Django 5.0.6 on 2024-07-28 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_mainpostforbot_enteties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpostforbot',
            old_name='enteties',
            new_name='entities',
        ),
    ]
