# Generated by Django 5.0.6 on 2024-07-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_rename_enteties_mainpostforbot_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpostforbot',
            name='entities',
            field=models.JSONField(blank=True, default={'entities': ''}),
        ),
    ]
