# Generated by Django 5.0.6 on 2024-08-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_mainpostforbot_entities'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('students', models.JSONField(blank=True)),
                ('students_count', models.IntegerField(blank=True)),
                ('status', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TgGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(blank=True)),
                ('user_name', models.IntegerField(blank=True)),
                ('group_for', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
