# Generated by Django 5.0.6 on 2024-08-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_availablecourse_course_tggroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablecourse',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
