# Generated by Django 5.0.6 on 2024-08-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='branch_name',
            field=models.ForeignKey(blank=True, default=1, on_delete=models.SET(''), to='pages.branch'),
            preserve_default=False,
        ),
    ]
