# Generated by Django 5.0.6 on 2024-08-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_subject_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='branch_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), to='pages.branch'),
        ),
    ]
