# Generated by Django 4.2.13 on 2024-08-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_subject_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='branch_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.branch'),
        ),
    ]
