# Generated by Django 4.2.13 on 2024-08-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_subject_count_alter_subject_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
