# Generated by Django 5.0.6 on 2024-08-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_subject_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branch',
            new_name='SubjectBranch',
        ),
    ]
