# Generated by Django 5.0.6 on 2024-08-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_rename_branch_subjectbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablecourse',
            name='teacher',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='availablecourse',
            name='teacher_entitie',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='course',
            name='description_entities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers_entities',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
