# Generated by Django 5.0.6 on 2024-08-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_availablecourse_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tggroup',
            old_name='user_id',
            new_name='group_id',
        ),
        migrations.RemoveField(
            model_name='tggroup',
            name='user_name',
        ),
        migrations.AddField(
            model_name='tggroup',
            name='group_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
