# Generated by Django 5.0.6 on 2024-08-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_rename_user_id_tggroup_group_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(blank=True)),
                ('forwarded_message_id', models.IntegerField(blank=True)),
                ('user_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
