# Generated by Django 5.0.6 on 2024-08-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_forwardmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardmessage',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
