# Generated by Django 5.0.6 on 2024-08-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_forwardmessage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablecourse',
            name='description_entities',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
